# **Basic Array Operations**

In [ ]:
import numpy as np)
print("Array from list: ",array_from_list)
array_from_list=np.array([1,2,3,4,5]

Array from list:  [1 2 3 4 5]


In [ ]:
array_with_range=np.arange(10)
print("Array with range: ",array_with_range)

Array with range:  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
zeroes_array=np.zeros((3,3))
print("Array of zeroes: \n",zeroes_array)

Array of zeroes: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_array=np.ones((2,5))
print("Array of ones: \n",ones_array)

Array of ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# **Array Operations**

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
add_result=np.add(a,b)
print("Addition: ",add_result)

Addition:  [5 7 9]


In [ ]:
sub_result = np.subtract(a, b)
print("Subtraction:", sub_result)

Subtraction: [-3 -3 -3]


In [ ]:
mul_result = np.multiply(a, b)
print("Multiplication:", mul_result)

Multiplication: [ 4 10 18]


In [ ]:
div_result = np.divide(a, b)

print("Division:", div_result)

Division: [0.25 0.4  0.5 ]


# **Array Reshaping**

In [ ]:
import numpy as np

array = np.arange(12)

print("Original array:", array)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
reshaped_array = array.reshape((3, 4))

print("Reshaped to 3x4:n", reshaped_array)

Reshaped to 3x4:n [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
reshaped_array_3d = array.reshape((2, 3, 2))

print("Reshaped to 2x3x2:\n", reshaped_array_3d)


Reshaped to 2x3x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


# **Indexing and Slicing**

In [ ]:
import numpy as np


array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("2D Array:In", array_2d)

2D Array:In [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
element=array_2d[1,2]
print("Element at (1,2): ",element)

Element at (1,2):  6
