# Create 2D arrays

In [1]:
import numpy as np

matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

matrix_sum = matrix1 + matrix2

matrix_diff = matrix1 - matrix2

matrix_product = matrix1 * matrix2

matrix_divide = matrix1 / matrix2

matrix_multiply = np.dot(matrix1, matrix2)

matrix1_transpose = np.transpose(matrix1)

diagonal_sum = np.trace(matrix1)

print("Matrix 1:\n", matrix1)

print("Matrix 2:\n", matrix2)

print("Matrix Sum:\n", matrix_sum)

print("Matrix Difference:\n", matrix_diff)

print("Matrix Element-wise Product:\n", matrix_product)

print("Matrix Element-wise Division:\n", matrix_divide)

print("Matrix Multiplication:\n", matrix_multiply)

print("Transpose of Matrix 1:\n", matrix1_transpose)

print("Sum of Diagonal Elements of Matrix 1:", diagonal_sum)

Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix Sum:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Difference:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Element-wise Product:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Element-wise Division:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of Matrix 1:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of Diagonal Elements of Matrix 1: 15
