# **2D arrays**

In [1]:
import numpy as np

two_dimensional_array = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12],

[13, 14, 15, 16]])

excluding_first_row = two_dimensional_array[1:]

excluding_last_column = two_dimensional_array[:, :-1]

column_1_2_in_row_2_3 = two_dimensional_array[1:3, 0:2]

column_2_3 = two_dimensional_array[:, 1:3]

elements_2_3_in_first_row = two_dimensional_array[0, 1:3]

descending_order = two_dimensional_array.ravel()[::-1][4:11]

print("Original 2D array:\n", two_dimensional_array)

print("Elements excluding the first row:\n", excluding_first_row)

print("Elements excluding the last column:\n", excluding_last_column)

print("Elements of the 1st and 2nd column in the 2nd and 3rd row:\n",

column_1_2_in_row_2_3)

print("Elements of the 2nd and 3rd column:\n", column_2_3)

print("2nd and 3rd element of the 1st row:\n", elements_2_3_in_first_row)

print("Elements from indices 4 to 10 in descending order:\n", descending_order)

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Elements excluding the first row:
 [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Elements excluding the last column:
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
Elements of the 1st and 2nd column in the 2nd and 3rd row:
 [[ 5  6]
 [ 9 10]]
Elements of the 2nd and 3rd column:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
2nd and 3rd element of the 1st row:
 [2 3]
Elements from indices 4 to 10 in descending order:
 [12 11 10  9  8  7  6]
